packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.12.1+sha512-+eHl6vUz4G6BDjw7MDR2iDN4+DcximPGfyflbHR16UsayXKIo0JXwQvTSOcfsMw1p0SLEN9prsSq7df/ztO3Xw==
loglevel: info
