/**
 * Skip and expected-failure maps for the yaml-test-suite.
 *
 * - SKIP: Tests that never run (not applicable to our implementation).
 * - XFAIL: Tests that run but are allowed to fail (known gaps to fix later).
 * - SKIP_ASSERTIONS: Tests where specific assertion types are skipped.
 *
 * Every entry must include a reason string explaining WHY.
 *
 * Generated from first triage run on 2026-03-14.
 * Total: ~440 test cases, 745/1231 assertions passing.
 */

/** Tests to skip entirely — not applicable to our implementation. */
export const SKIP: Record<string, string> = {};

/** Tests expected to fail at parse level — known gaps to fix later. */
export const XFAIL: Record<string, string> = {
	// Parser rejects valid YAML (16)
	"2JQS": "Parser rejects valid YAML: Block Mapping with Missing Keys",
	"2SXE": "Parser rejects valid YAML: Anchors With Colon in Name",
	"3RLN/01": "Parser rejects valid YAML: Leading tabs in double quoted",
	"3RLN/04": "Parser rejects valid YAML: Leading tabs in double quoted",
	"6CA3": "Parser rejects valid YAML: Tab indented top flow",
	"DE56/02": "Parser rejects valid YAML: Trailing tabs in double quoted",
	"DE56/03": "Parser rejects valid YAML: Trailing tabs in double quoted",
	"DK95/04": "Parser rejects valid YAML: Tabs that look like indentation",
	"DK95/07": "Parser rejects valid YAML: Tabs that look like indentation",
	HS5T: "Parser rejects valid YAML: Spec Example 7.12. Plain Lines",
	"KH5V/01": "Parser rejects valid YAML: Inline tabs in double quoted",
	KK5P: "Parser rejects valid YAML: Various combinations of explicit block mappings",
	Q5MG: "Parser rejects valid YAML: Tab at beginning of line followed by a flow mapping",
	S3PD: "Parser rejects valid YAML: Spec Example 8.18. Implicit Block Mapping Entries",
	V9D5: "Parser rejects valid YAML: Spec Example 8.19. Compact Block Mappings",
	W5VH: "Parser rejects valid YAML: Allowed characters in alias",

	// Parser accepts invalid YAML (87)
	"236B": "Parser accepts invalid YAML: Invalid value after mapping",
	"2CMS": "Parser accepts invalid YAML: Invalid mapping in plain multiline",
	"2G84/00": "Parser accepts invalid YAML: Literal modifers",
	"2G84/01": "Parser accepts invalid YAML: Literal modifers",
	"3HFZ": "Parser accepts invalid YAML: Invalid content after document end marker",
	"4H7K": "Parser accepts invalid YAML: Flow sequence with invalid extra closing bracket",
	"4HVU": "Parser accepts invalid YAML: Wrong indendation in Sequence",
	"4JVG": "Parser accepts invalid YAML: Scalar value with two anchors",
	"5LLU": "Parser accepts invalid YAML: Block scalar with wrong indented line after spaces only",
	"5TRB": "Parser accepts invalid YAML: Invalid document-start marker in doublequoted tring",
	"5U3A": "Parser accepts invalid YAML: Sequence on same Line as Mapping Key",
	"62EZ": "Parser accepts invalid YAML: Invalid block mapping key on same line as previous key",
	"6JTT": "Parser accepts invalid YAML: Flow sequence without closing bracket",
	"6S55": "Parser accepts invalid YAML: Invalid scalar at the end of sequence",
	"7LBH": "Parser accepts invalid YAML: Multiline double quoted implicit keys",
	"7MNF": "Parser accepts invalid YAML: Missing colon",
	"8XDJ": "Parser accepts invalid YAML: Comment in plain multiline value",
	"9C9N": "Parser accepts invalid YAML: Wrong indented flow sequence",
	"9CWY": "Parser accepts invalid YAML: Invalid scalar at the end of mapping",
	"9HCY": "Parser accepts invalid YAML: Need document footer before directives",
	"9JBA": "Parser accepts invalid YAML: Invalid comment after end of flow sequence",
	"9KBC": "Parser accepts invalid YAML: Mapping starting at --- line",
	"9MAG": "Parser accepts invalid YAML: Flow sequence with invalid comma at the beginning",
	"9MMA": "Parser accepts invalid YAML: Directive by itself with no document",
	"9MQT/01": "Parser accepts invalid YAML: Scalar doc with '...' in content",
	B63P: "Parser accepts invalid YAML: Directive without document",
	BD7L: "Parser accepts invalid YAML: Invalid mapping after sequence",
	BF9H: "Parser accepts invalid YAML: Trailing comment in multiline plain scalar",
	BS4K: "Parser accepts invalid YAML: Comment between plain scalar lines",
	C2SP: "Parser accepts invalid YAML: Flow Mapping Key on two lines",
	CML9: "Parser accepts invalid YAML: Missing comma in flow",
	CTN5: "Parser accepts invalid YAML: Flow sequence with invalid extra comma",
	CVW2: "Parser accepts invalid YAML: Invalid comment after comma",
	CXX2: "Parser accepts invalid YAML: Mapping with anchor on document start line",
	D49Q: "Parser accepts invalid YAML: Multiline single quoted implicit keys",
	DK4H: "Parser accepts invalid YAML: Implicit key followed by newline",
	"DK95/01": "Parser accepts invalid YAML: Tabs that look like indentation",
	"DK95/06": "Parser accepts invalid YAML: Tabs that look like indentation",
	DMG6: "Parser accepts invalid YAML: Wrong indendation in Map",
	EB22: "Parser accepts invalid YAML: Missing document-end marker before directive",
	EW3V: "Parser accepts invalid YAML: Wrong indendation in mapping",
	G5U8: "Parser accepts invalid YAML: Plain dashes in flow sequence",
	G7JE: "Parser accepts invalid YAML: Multiline implicit keys",
	G9HC: "Parser accepts invalid YAML: Invalid anchor in zero indented sequence",
	GDY7: "Parser accepts invalid YAML: Comment that looks like a mapping key",
	GT5M: "Parser accepts invalid YAML: Node anchor in sequence",
	H7J7: "Parser accepts invalid YAML: Node anchor not indented",
	H7TQ: "Parser accepts invalid YAML: Extra words on %YAML directive",
	HU3P: "Parser accepts invalid YAML: Invalid Mapping in plain scalar",
	JKF3: "Parser accepts invalid YAML: Multiline unidented double quoted block key",
	JY7Z: "Parser accepts invalid YAML: Trailing content that looks like a mapping",
	KS4U: "Parser accepts invalid YAML: Invalid item after end of flow sequence",
	LHL4: "Parser accepts invalid YAML: Invalid tag",
	"MUS6/00": "Parser accepts invalid YAML: Directive variants",
	"MUS6/01": "Parser accepts invalid YAML: Directive variants",
	N4JP: "Parser accepts invalid YAML: Bad indentation in mapping",
	N782: "Parser accepts invalid YAML: Invalid document markers in flow style",
	P2EQ: "Parser accepts invalid YAML: Invalid sequene item on same line as previous item",
	Q4CL: "Parser accepts invalid YAML: Trailing content after quoted value",
	QB6E: "Parser accepts invalid YAML: Wrong indented multiline quoted scalar",
	QLJ7: "Parser accepts invalid YAML: Tag shorthand used in documents but only defined in the first",
	RHX7: "Parser accepts invalid YAML: YAML directive without document end marker",
	RXY3: "Parser accepts invalid YAML: Invalid document-end marker in single quoted string",
	S4GJ: "Parser accepts invalid YAML: Invalid text after block scalar indicator",
	S98Z: "Parser accepts invalid YAML: Block scalar with more spaces than first content line",
	SF5V: "Parser accepts invalid YAML: Duplicate YAML directive",
	SR86: "Parser accepts invalid YAML: Anchor plus Alias",
	SU5Z: "Parser accepts invalid YAML: Comment without whitespace after doublequoted scalar",
	SU74: "Parser accepts invalid YAML: Anchor and alias as mapping key",
	SY6V: "Parser accepts invalid YAML: Anchor before sequence entry on same line",
	T833: "Parser accepts invalid YAML: Flow mapping missing a separating comma",
	TD5N: "Parser accepts invalid YAML: Invalid scalar after sequence",
	U44R: "Parser accepts invalid YAML: Bad indentation in mapping (2)",
	U99R: "Parser accepts invalid YAML: Invalid comma in tag",
	"VJP3/00": "Parser accepts invalid YAML: Flow collections over many lines",
	W9L4: "Parser accepts invalid YAML: Literal block scalar with more spaces in first line",
	X4QW: "Parser accepts invalid YAML: Comment without whitespace after block scalar indicator",
	"Y79Y/003": "Parser accepts invalid YAML: Tabs in various contexts",
	"Y79Y/004": "Parser accepts invalid YAML: Tabs in various contexts",
	"Y79Y/005": "Parser accepts invalid YAML: Tabs in various contexts",
	"Y79Y/006": "Parser accepts invalid YAML: Tabs in various contexts",
	"Y79Y/007": "Parser accepts invalid YAML: Tabs in various contexts",
	"Y79Y/008": "Parser accepts invalid YAML: Tabs in various contexts",
	YJV2: "Parser accepts invalid YAML: Dash in flow sequence",
	ZL4Z: "Parser accepts invalid YAML: Invalid nested mapping",
	ZVH3: "Parser accepts invalid YAML: Wrong indented sequence item",
	ZXT5: "Parser accepts invalid YAML: Implicit key followed by newline and adjacent value",
};

/**
 * Tests to skip specific assertions for.
 * - "json" — skip JSON output comparison
 * - "output" — skip out.yaml canonical output comparison
 * - "roundtrip" — skip stringify roundtrip comparison
 */
export const SKIP_ASSERTIONS: Record<string, string[]> = {
	"229Q": ["json", "output"],
	"26DV": ["json", "output"],
	"27NA": ["output"],
	"2AUY": ["output"],
	"2EBW": ["output"],
	"2G84/03": ["json", "roundtrip"],
	"2LFX": ["output"],
	"2XXW": ["output"],
	"33X3": ["output"],
	"35KP": ["json", "output"],
	"36F6": ["json", "output"],
	"3GZX": ["json"],
	"3MYT": ["json", "output"],
	"3R3P": ["output"],
	"3RLN/00": ["json"],
	"3RLN/02": ["json"],
	"3RLN/03": ["json"],
	"3RLN/05": ["json"],
	"3UYS": ["output"],
	"4ABK": ["output"],
	"4CQQ": ["json", "output"],
	"4FJ6": ["output"],
	"4Q9F": ["output"],
	"4QFQ": ["roundtrip"],
	"4V8U": ["output"],
	"4WA9": ["json", "output", "roundtrip"],
	"4ZYM": ["json", "output"],
	"52DL": ["output"],
	"57H4": ["json", "output"],
	"58MP": ["output"],
	"5BVJ": ["output"],
	"5GBF": ["json", "output"],
	"5MUD": ["json", "output"],
	"5T43": ["json", "output"],
	"5TYM": ["json"],
	"5WE3": ["json", "output", "roundtrip"],
	"652Z": ["output"],
	"6BFJ": ["output"],
	"6FWR": ["json", "output"],
	"6H3V": ["output"],
	"6HB6": ["output"],
	"6JQW": ["output"],
	"6JWB": ["json", "output"],
	"6KGN": ["json", "output"],
	"6LVF": ["output"],
	"6M2F": ["output"],
	"6SLA": ["output", "roundtrip"],
	"6VJK": ["json", "output"],
	"6WLZ": ["json", "output"],
	"6WPF": ["json", "output"],
	"6XDY": ["json", "output"],
	"6ZKB": ["json"],
	"735Y": ["json", "output"],
	"74H7": ["output"],
	"753E": ["output"],
	"7A4E": ["json", "output"],
	"7BMT": ["output"],
	"7BUB": ["output"],
	"7FWL": ["output"],
	"7T8X": ["json", "output"],
	"7TMG": ["output"],
	"7W2P": ["output"],
	"7Z25": ["json", "output"],
	"7ZZ5": ["json", "output"],
	"82AN": ["json", "output"],
	"87E4": ["json", "output"],
	"8CWC": ["output"],
	"8G76": ["json", "output"],
	"8KB6": ["json", "output"],
	"8QBE": ["output"],
	"8UDB": ["json", "output"],
	"8XYN": ["output"],
	"93JH": ["json", "output"],
	"93WF": ["output"],
	"96L6": ["output"],
	"96NN/00": ["output"],
	"96NN/01": ["output"],
	"98YD": ["json", "output"],
	"9BXH": ["json", "output"],
	"9DXL": ["json"],
	"9KAX": ["json", "output"],
	"9MMW": ["output", "roundtrip"],
	"9MQT/00": ["output"],
	"9SA2": ["json", "output"],
	"9TFX": ["json", "output"],
	"9U5K": ["output"],
	"9WXW": ["json", "output"],
	"9YRD": ["json", "output"],
	A2M4: ["json", "output"],
	A6F9: ["output"],
	A984: ["json", "output"],
	AB8U: ["json", "output"],
	AVM7: ["json"],
	AZ63: ["json"],
	B3HG: ["output"],
	BEC7: ["output"],
	BU8L: ["output"],
	C2DT: ["json", "output"],
	C4HZ: ["json", "output"],
	CC74: ["output"],
	CFD4: ["output"],
	CN3R: ["json", "output"],
	CPZ3: ["output"],
	CT4Q: ["json", "output"],
	CUP7: ["output"],
	D83L: ["output"],
	D88J: ["output"],
	DBG4: ["output"],
	DC7X: ["output"],
	"DE56/00": ["json", "output"],
	"DE56/01": ["json", "output"],
	"DE56/04": ["json", "output"],
	"DE56/05": ["json", "output"],
	DFF7: ["output"],
	DK3J: ["json", "output"],
	"DK95/02": ["json"],
	"DK95/08": ["json", "roundtrip"],
	DWX9: ["json", "output"],
	E76Z: ["json", "output"],
	EHF6: ["output"],
	EX5H: ["json", "output"],
	EXG3: ["json", "output"],
	F2C7: ["output"],
	F3CP: ["output"],
	F6MC: ["json", "roundtrip"],
	F8F9: ["output"],
	FBC9: ["json", "output"],
	FH7J: ["output"],
	FP8R: ["json", "output"],
	FTA2: ["output"],
	G4RS: ["output", "roundtrip"],
	G992: ["output"],
	H2RW: ["json", "output"],
	H3Z8: ["output"],
	"HM87/00": ["output"],
	"HM87/01": ["output"],
	HMK4: ["output"],
	HMQ5: ["output"],
	HWV9: ["json", "output"],
	J3BT: ["output", "roundtrip"],
	J7PZ: ["output"],
	J9HZ: ["output"],
	"JEF9/00": ["json", "output", "roundtrip"],
	"JEF9/01": ["output", "roundtrip"],
	"JEF9/02": ["output", "roundtrip"],
	JHB9: ["json", "output"],
	JQ4R: ["output"],
	JTV5: ["json", "output"],
	K3WX: ["json", "output"],
	K527: ["output"],
	K54U: ["output"],
	K858: ["output", "roundtrip"],
	"KH5V/02": ["output"],
	KSS4: ["json", "output"],
	"L24T/00": ["json"],
	"L24T/01": ["json"],
	L383: ["json", "output"],
	L94M: ["output"],
	L9U5: ["json", "output"],
	LE5A: ["json"],
	LP6E: ["output"],
	LQZ7: ["json", "output"],
	LX3P: ["output"],
	M29M: ["output"],
	"M2N8/00": ["output"],
	"M2N8/01": ["output"],
	M5C3: ["output"],
	M5DY: ["output"],
	M6YH: ["json", "output"],
	M7A3: ["json"],
	M7NX: ["output"],
	MJS9: ["json", "output"],
	"MUS6/02": ["output"],
	"MUS6/03": ["output"],
	"MUS6/04": ["output"],
	"MUS6/05": ["output"],
	"MUS6/06": ["output"],
	MYW6: ["output"],
	NAT4: ["json", "roundtrip"],
	NB6Z: ["json", "output"],
	NJ66: ["json", "output"],
	NP9H: ["json", "output"],
	P2AD: ["output", "roundtrip"],
	P76L: ["json", "output"],
	PBJ2: ["output"],
	PRH3: ["json", "output", "roundtrip"],
	PUW8: ["json", "output"],
	PW8X: ["output"],
	Q88A: ["output"],
	Q8AD: ["json", "output"],
	Q9WF: ["output"],
	QF4Y: ["json", "output"],
	QT73: ["json", "output"],
	R4YG: ["json", "output", "roundtrip"],
	R52L: ["output"],
	RLU9: ["json", "output"],
	RTP8: ["output"],
	RZP5: ["output"],
	RZT7: ["json", "output"],
	S4JQ: ["output"],
	S7BG: ["output"],
	S9E8: ["json", "output"],
	SBG9: ["output"],
	SKE5: ["json", "output"],
	"SM9W/00": ["json", "output"],
	"SM9W/01": ["output"],
	SSW6: ["output"],
	T26H: ["json", "output"],
	T4YY: ["json", "output", "roundtrip"],
	T5N4: ["output"],
	TL85: ["json", "output"],
	TS54: ["output"],
	U3C3: ["output"],
	U3XV: ["output"],
	U9NS: ["json"],
	UDR7: ["output"],
	UGM3: ["json", "output"],
	UT92: ["json", "output"],
	UV7Q: ["json", "output"],
	"VJP3/01": ["output"],
	W42U: ["json", "output"],
	W4TN: ["json", "output"],
	WZ62: ["json", "output"],
	X38W: ["output"],
	X8DW: ["json", "output"],
	XLQ9: ["json", "output"],
	XV9V: ["json", "output"],
	XW4D: ["output"],
	Y2GN: ["json", "output"],
	"Y79Y/001": ["output"],
	Z67P: ["output"],
	Z9M4: ["output"],
	ZK9H: ["output"],
	ZWK4: ["output"],
};
