/**
 * Skip and expected-failure maps for the yaml-test-suite.
 *
 * - SKIP: Tests that never run (not applicable to our implementation).
 * - XFAIL: Tests that run but are allowed to fail (known gaps to fix later).
 * - SKIP_ASSERTIONS: Tests where specific assertion types are skipped.
 *
 * Every entry must include a reason string explaining WHY.
 *
 * Generated from first triage run on 2026-03-14.
 * Updated: multi-document harness, block scalar, tagged empty value, anchor name, tab handling, block mapping fixes.
 */

/** Tests to skip entirely — not applicable to our implementation. */
export const SKIP: Record<string, string> = {};

/** Tests expected to fail at parse level — known gaps to fix later. */
export const XFAIL: Record<string, string> = {
	// Parser accepts invalid YAML (29)
	"4HVU": "Parser accepts invalid YAML: Wrong indendation in Sequence",
	"4JVG": "Parser accepts invalid YAML: Scalar value with two anchors",
	"5LLU": "Parser accepts invalid YAML: Block scalar with wrong indented line after spaces only",
	"9C9N": "Parser accepts invalid YAML: Wrong indented flow sequence",
	"9KBC": "Parser accepts invalid YAML: Mapping starting at --- line",
	BS4K: "Parser accepts invalid YAML: Comment between plain scalar lines",
	C2SP: "Parser accepts invalid YAML: Flow Mapping Key on two lines",
	CML9: "Parser accepts invalid YAML: Missing comma in flow",
	CXX2: "Parser accepts invalid YAML: Mapping with anchor on document start line",
	DMG6: "Parser accepts invalid YAML: Wrong indendation in Map",
	EW3V: "Parser accepts invalid YAML: Wrong indendation in mapping",
	G5U8: "Parser accepts invalid YAML: Plain dashes in flow sequence",
	G9HC: "Parser accepts invalid YAML: Invalid anchor in zero indented sequence",
	H7J7: "Parser accepts invalid YAML: Node anchor not indented",
	N4JP: "Parser accepts invalid YAML: Bad indentation in mapping",
	QB6E: "Parser accepts invalid YAML: Wrong indented multiline quoted scalar",
	QLJ7: "Parser accepts invalid YAML: Tag shorthand used in documents but only defined in the first",
	S98Z: "Parser accepts invalid YAML: Block scalar with more spaces than first content line",
	SR86: "Parser accepts invalid YAML: Anchor plus Alias",
	SU74: "Parser accepts invalid YAML: Anchor and alias as mapping key",
	SY6V: "Parser accepts invalid YAML: Anchor before sequence entry on same line",
	T833: "Parser accepts invalid YAML: Flow mapping missing a separating comma",
	U44R: "Parser accepts invalid YAML: Bad indentation in mapping (2)",
	U99R: "Parser accepts invalid YAML: Invalid comma in tag",
	"VJP3/00": "Parser accepts invalid YAML: Flow collections over many lines",
	W9L4: "Parser accepts invalid YAML: Literal block scalar with more spaces in first line",
	"Y79Y/009": "Parser accepts invalid YAML: Tab as block indentation after value indicator",
	YJV2: "Parser accepts invalid YAML: Dash in flow sequence",
	ZVH3: "Parser accepts invalid YAML: Wrong indented sequence item",
};

/**
 * Tests to skip specific assertions for.
 * - "json" — skip JSON output comparison
 * - "output" — skip out.yaml canonical output comparison
 * - "roundtrip" — skip stringify roundtrip comparison
 */
export const SKIP_ASSERTIONS: Record<string, string[]> = {
	HS5T: ["output"],
	"26DV": ["output"],
	"27NA": ["output"],
	"2AUY": ["output"],
	"2LFX": ["output"],
	"2SXE": ["output"],
	"2XXW": ["output"],
	"33X3": ["output"],
	"35KP": ["output"],
	"36F6": ["output"],
	"3MYT": ["output"],
	"3R3P": ["output"],
	"3UYS": ["output"],
	"4ABK": ["output"],
	"4CQQ": ["output"],
	"4FJ6": ["output"],
	"4Q9F": ["output"],
	"4QFQ": ["roundtrip"],
	"4V8U": ["output"],
	"4WA9": ["output"],
	"4ZYM": ["output"],
	"52DL": ["output"],
	"57H4": ["output"],
	"5BVJ": ["output"],
	"5GBF": ["output"],
	"5MUD": ["output"],
	"5WE3": ["output", "roundtrip"],
	"652Z": ["output"],
	"6BFJ": ["output"],
	"6FWR": ["output"],
	"6H3V": ["output"],
	"6HB6": ["output"],
	"6JQW": ["output"],
	"6JWB": ["output"],
	"6KGN": ["output"],
	"6LVF": ["output"],
	"6M2F": ["output"],
	"6SLA": ["output", "roundtrip"],
	"6VJK": ["output"],
	"6WLZ": ["output"],
	"6WPF": ["output", "roundtrip"],
	"6XDY": ["output"],
	"735Y": ["output"],
	"74H7": ["output"],
	"753E": ["output"],
	"7A4E": ["output", "roundtrip"],
	"7BMT": ["output"],
	"7BUB": ["output"],
	"7FWL": ["output"],
	"7T8X": ["output"],
	"7TMG": ["output"],
	"7W2P": ["output"],
	"7Z25": ["output"],
	"7ZZ5": ["output"],
	"82AN": ["output"],
	"87E4": ["output"],
	"8CWC": ["output"],
	"8G76": ["output"],
	"8KB6": ["output"],
	"8QBE": ["output"],
	"8UDB": ["output"],
	"8XYN": ["output"],
	"93WF": ["output"],
	"96L6": ["output"],
	"96NN/00": ["output"],
	"96NN/01": ["output"],
	"98YD": ["output"],
	"9BXH": ["output"],
	"9KAX": ["output"],
	"9MMW": ["output", "roundtrip"],
	"9MQT/00": ["output"],
	"9SA2": ["output"],
	"9TFX": ["output", "roundtrip"],
	"9U5K": ["output"],
	"9WXW": ["output"],
	"9YRD": ["output"],
	A2M4: ["output"],
	A6F9: ["output"],
	AB8U: ["output"],
	B3HG: ["output"],
	BEC7: ["output"],
	BU8L: ["output"],
	C2DT: ["output"],
	C4HZ: ["output"],
	CC74: ["output"],
	CFD4: ["output", "roundtrip"],
	CN3R: ["output"],
	CPZ3: ["output"],
	CUP7: ["output"],
	D83L: ["output"],
	D88J: ["output"],
	DBG4: ["output"],
	DC7X: ["output"],
	"DE56/00": ["output"],
	"DE56/01": ["output"],
	"DE56/02": ["output"],
	"DE56/03": ["output"],
	"DE56/04": ["output"],
	"DE56/05": ["output"],
	DFF7: ["output"],
	DK3J: ["output"],
	"DK95/08": ["roundtrip"],
	DWX9: ["output"],
	E76Z: ["output"],
	EHF6: ["output"],
	EX5H: ["output"],
	EXG3: ["output"],
	F2C7: ["output"],
	F3CP: ["output"],
	F6MC: ["roundtrip"],
	F8F9: ["output"],
	FBC9: ["output"],
	FH7J: ["output"],
	FP8R: ["output"],
	FTA2: ["output"],
	G4RS: ["output", "roundtrip"],
	G992: ["output"],
	H2RW: ["output"],
	H3Z8: ["output"],
	HMK4: ["output"],
	HMQ5: ["output"],
	HWV9: ["output"],
	J3BT: ["output", "roundtrip"],
	J7PZ: ["output"],
	J9HZ: ["output"],
	"JEF9/00": ["output"],
	"JEF9/01": ["output", "roundtrip"],
	"JEF9/02": ["output", "roundtrip"],
	JHB9: ["output"],
	JQ4R: ["output"],
	JTV5: ["output"],
	K3WX: ["output"],
	K527: ["output"],
	K54U: ["output"],
	K858: ["output", "roundtrip"],
	"KH5V/01": ["output"],
	"KH5V/02": ["output"],
	KK5P: ["output", "roundtrip"],
	KSS4: ["output"],
	L383: ["output"],
	L94M: ["output"],
	L9U5: ["output"],
	LP6E: ["output"],
	LQZ7: ["output"],
	LX3P: ["output"],
	M29M: ["output"],
	"M2N8/00": ["output"],
	"M2N8/01": ["output"],
	M5C3: ["output"],
	M5DY: ["output"],
	M6YH: ["output"],
	M7NX: ["output"],
	MJS9: ["output"],
	"MUS6/02": ["output"],
	"MUS6/03": ["output"],
	"MUS6/04": ["output"],
	"MUS6/05": ["output"],
	"MUS6/06": ["output"],
	MYW6: ["output"],
	NAT4: ["roundtrip"],
	NB6Z: ["output"],
	NJ66: ["output"],
	NP9H: ["output"],
	P2AD: ["output", "roundtrip"],
	P76L: ["output"],
	PBJ2: ["output"],
	PRH3: ["output", "roundtrip"],
	PUW8: ["output"],
	PW8X: ["output"],
	Q88A: ["output"],
	Q8AD: ["output"],
	Q9WF: ["output"],
	QT73: ["output"],
	R4YG: ["output", "roundtrip"],
	R52L: ["output"],
	RLU9: ["output"],
	RTP8: ["output"],
	RZP5: ["output"],
	RZT7: ["output"],
	S4JQ: ["output"],
	S7BG: ["output"],
	S9E8: ["output"],
	SBG9: ["output"],
	SKE5: ["output"],
	"SM9W/00": ["output"],
	"SM9W/01": ["output"],
	SSW6: ["output"],
	T26H: ["output"],
	T4YY: ["output", "roundtrip"],
	T5N4: ["output"],
	TL85: ["output", "roundtrip"],
	TS54: ["output"],
	U3C3: ["output"],
	U3XV: ["output"],
	UDR7: ["output"],
	UGM3: ["output"],
	UT92: ["output"],
	UV7Q: ["output"],
	"VJP3/01": ["output"],
	W42U: ["output"],
	W4TN: ["output"],
	WZ62: ["output"],
	X38W: ["output"],
	X8DW: ["output"],
	XLQ9: ["output"],
	XV9V: ["output"],
	XW4D: ["output"],
	Y2GN: ["output"],
	"Y79Y/001": ["output"],
	Z67P: ["output"],
	Z9M4: ["output"],
	ZK9H: ["output"],
	ZWK4: ["output"],
};
